[KeyboardConfig]
#general configs for the keyboard goes here
# vjoyID = <ID of vjoy controller>
vjoyID = 1

[[buttons]]
# a specific keyboard mapping would follow this structure:
# from = <scan code of key>
# to = button ID
# type = <0 = "hold"; 1 = "toggle on press">    (optional, default = 0)

from = 30
to = 1
type = 0

[[axes]]
# a specific axis mapping would follow this structure:
# axis = axis ID, #TODO add ID's from pyvjoy to readme
# increase = <scan code of key to increase axis>
# decrease = <scan code of key to decrease axis> 
# key = <rate that the key increases the value by>
# decay = <rate of decay (towards zero) when no button is pressed>

axis = 48
increase = 17
decrease = 31
key = 0.05
decay = 0.05

[[pov]]
# a specific POV mapping would follow this structure:
# button = scan code of button that triggers POV
# pov_value = pov_value that is set in code #TODO: figure out units!

button = 1
pov_value = 87