[KeyboardConfig]
#general configs for the keyboard goes here
# vjoyID = <ID of vjoy controller>
vjoyID = 1

[[buttons]]
# a specific keyboard mapping would follow this structure:
# from = <scan code of key>
# to = button ID
# type = <0 = "hold"; 1 = "toggle on press">    (optional, default = 0)

from = 30
to = 1
type = 0

[[axes]]
# a specific axis mapping would follow this structure:
# axis = axis ID, #TODO add ID's from pyvjoy to readme
# increase = <scan code of key to increase axis>
# decrease = <scan code of key to decrease axis> 
# key = <rate that the key increases the value by>
# decay = <rate of decay (towards zero) when no button is pressed>

axis = 0x30
increase = 17
decrease = 31
key = 0.05
decay = 0.05

[[cont_pov]]
# a specific continous POV mapping would follow this structure:
# scan_code = scan code of button that triggers POV
# pov_value = angle of POV (in 1/100th of degrees, 45 degrees = 4500)
# pov_id = the ID of the pov you want this button to affect (optional, default = most recent axis ID)

scan_code = 72
pov_value = 0
pov_id = 1

[[cont_pov]]
scan_code = 80
pov_value = 18000

[[cont_pov]]
scan_code = 75
pov_value = 27000

[[cont_pov]]
scan_code = 77
pov_value = 9000