[KeyboardConfig]
#general configs for the keyboard goes here

[[KeyboardConfig.buttons]]
# a specific keyboard mapping would follow this structure: (note: datatypes may be different)
from = -1
to = "A"
